### ISSUE TITLE
US4: Unfinished tasks roll over to the next day

### ISSUE THREAD

**Issue by wandwan** [CSE-110-Winter-2024/project-team-25#23]
As a busy individual, I want my unfinished tasks to automatically roll over to the next day, So that I can ensure continuity in my task management and do not need to manually re-enter tasks.

Scenario 1: Automatic Rollover at End of Day
Given I have tasks listed for the current day,
  And some of these tasks are not marked as completed by the end of the day,
When the day ends,
Then the uncompleted tasks should automatically appear in the task list for the next day,
  And they should be prioritized at the top of the list or marked as overdue.

Scenario 2: Manual Task Completion on Following Day
Given some tasks have rolled over from the previous day,
  And they are now displayed on the current day's task list,
When I complete and mark one of these tasks as done,
Then it should be removed from the current day’s list,
  And it should be recorded in the completed tasks history or log.

 - [x] CSE-110-Winter-2024/project-team-25#22 
 - [x] CSE-110-Winter-2024/project-team-25#24 
 - [x] CSE-110-Winter-2024/project-team-25#21 
 - [x] CSE-110-Winter-2024/project-team-25#20 
 - [ ] CSE-110-Winter-2024/project-team-25#25
