### ISSUE TITLE
US1: Add a display for all goals of the day

### ISSUE THREAD

**Issue by dillwang** [CSE-110-Winter-2024/project-team-25#26]
As a user, I want to see all of my goals for the day (either finished or unfinished) when I open my application
So that I know what to do for the day.
- [x] CSE-110-Winter-2024/project-team-25#27 
- [x] CSE-110-Winter-2024/project-team-25#28 
- [x] CSE-110-Winter-2024/project-team-25#29  
- [x] CSE-110-Winter-2024/project-team-25#5 
- [x] #30 
- [x] #31
- [x] #32
- [x] #40
